# Generated by Django 3.2 on 2021-05-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_topping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='topic',
            new_name='pizza',
        ),
    ]
