# Generated by Django 3.2 on 2021-05-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20210503_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='name',
            new_name='text',
        ),
    ]
